# Generated by Django 4.0.6 on 2022-07-29 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeshare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property_listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=128)),
                ('address_2', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=144)),
                ('title', models.CharField(max_length=144)),
                ('active', models.BooleanField(default=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=19)),
                ('pool', models.BooleanField(default=True)),
                ('wifi', models.BooleanField(default=True)),
                ('kitchen', models.BooleanField(default=True)),
                ('free_parking', models.BooleanField(default=True)),
                ('jacuzzi', models.BooleanField(default=True)),
                ('washer', models.BooleanField(default=True)),
                ('air_conditioning', models.BooleanField(default=True)),
                ('self_check_in', models.BooleanField(default=True)),
                ('workspace', models.BooleanField(default=True)),
                ('pets_allowed', models.BooleanField(default=True)),
                ('smoke_alarm', models.BooleanField(default=True)),
                ('carbon_monoxide_alarm', models.BooleanField(default=True)),
                ('fire_extinguisher', models.BooleanField(default=True)),
                ('first_aid_kit', models.BooleanField(default=True)),
                ('crib_and_high_chair', models.BooleanField(default=True)),
                ('bathtub', models.BooleanField(default=True)),
                ('wine_glasses', models.BooleanField(default=True)),
                ('coffee_maker', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.IntegerField()),
                ('bio', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='property_follow',
            field=models.ManyToManyField(related_name='follow_property', to='homeshare.property_listing'),
        ),
    ]
