# Generated by Django 4.0.6 on 2022-08-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeshare', '0003_profile_profilepic_profile_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='Blank-User.jpg', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='bathtub',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='carbon_monoxide_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='coffee_maker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='creation_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='crib_and_high_chair',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='fire_extinguisher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='first_aid_kit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='free_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='jacuzzi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='self_check_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='smoke_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='washer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='wine_glasses',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='workspace',
            field=models.BooleanField(default=False),
        ),
    ]
