# Generated by Django 4.0.6 on 2022-08-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeshare', '0004_alter_profile_profilepic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_listing',
            old_name='starting_bid',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='property_listing',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='property_listing',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='image_url',
            field=models.ImageField(default='pic1.jpg', upload_to='listing_images'),
        ),
    ]
