# Generated by Django 4.0.6 on 2022-08-02 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeshare', '0005_rename_starting_bid_property_listing_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_listing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='image_url_2',
            field=models.ImageField(default='pic1.jpg', upload_to='listing_images'),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='image_url_3',
            field=models.ImageField(default='pic1.jpg', upload_to='listing_images'),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='image_url_4',
            field=models.ImageField(default='pic1.jpg', upload_to='listing_images'),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='image_url_5',
            field=models.ImageField(default='pic1.jpg', upload_to='listing_images'),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='image_url_6',
            field=models.ImageField(default='pic1.jpg', upload_to='listing_images'),
        ),
    ]
